"use client";
import {useState} from "react";import Link from "next/link";import {ChevronRight,Code2,Monitor,Moon,Smartphone,Sun} from "lucide-react";import type {RegistryItem} from "@/registry/components";import {ComponentPreview} from "./component-preview";import {CopyButton} from "./copy-button";
function componentSource(item: RegistryItem) { const symbol = item.name.replaceAll(" ", ""); return `"use client";

import { motion } from "motion/react";
import { cn } from "@/lib/utils";

export interface ${symbol}Props extends React.HTMLAttributes<HTMLDivElement> {
  variant?: "default" | "quiet" | "expressive";
}

export function ${symbol}({ className, children, variant = "default", ...props }: ${symbol}Props) {
  return (
    <motion.div
      className={cn("relative", className)}
      initial={{ opacity: 0, y: 8 }}
      animate={{ opacity: 1, y: 0 }}
      whileHover={{ y: -2 }}
      transition={{ type: "spring", stiffness: 280, damping: 24 }}
      data-variant={variant}
      {...props}
    >
      {children}
    </motion.div>
  );
}`; }
export function ComponentDoc({item,related}:{item:RegistryItem;related:RegistryItem[]}){const [mode,setMode]=useState<"desktop"|"mobile">("desktop"),[dark,setDark]=useState(false),[tab,setTab]=useState<"preview"|"code">("preview");const cmd=`pnpm dlx themaginui add ${item.slug}`;const source=componentSource(item);return <main><div className="page-wrap py-7 md:py-10"><div className="flex items-center gap-2 overflow-hidden whitespace-nowrap mono text-[9px] uppercase muted"><Link className="hover:text-[var(--ink)]" href="/components">Components</Link><ChevronRight className="shrink-0" size={11}/><span>{item.category}</span><ChevronRight className="shrink-0" size={11}/><span className="truncate text-[var(--ink)]">{item.name}</span></div><div className="mt-10 flex flex-col justify-between gap-7 border-b hairline pb-10 md:flex-row md:items-end"><div><span className="section-kicker">{item.category} / {item.complexity}</span><h1 className="display mt-4 text-5xl leading-[.95] md:text-7xl">{item.name}</h1><p className="mt-4 max-w-xl text-base leading-7 muted">{item.description}</p></div><div className="shrink-0"><CopyButton value={cmd} label="Copy install command"/></div></div>
 <div className="mt-8 grid gap-12 xl:grid-cols-[minmax(0,1fr)_240px]"><article className="min-w-0"><div className="overflow-hidden rounded-xl border hairline bg-[var(--raised)]"><div className="flex flex-wrap items-center justify-between gap-2 border-b hairline p-2"><div className="flex gap-1" role="tablist" aria-label="Component view"><button role="tab" aria-selected={tab==="preview"} onClick={()=>setTab("preview")} className={`btn min-h-8 px-3 text-[10px] ${tab==="preview"?"btn-primary":""}`}><Monitor size={13}/> Preview</button><button role="tab" aria-selected={tab==="code"} onClick={()=>setTab("code")} className={`btn min-h-8 px-3 text-[10px] ${tab==="code"?"btn-primary":""}`}><Code2 size={13}/> Code</button></div><div className="flex gap-1"><button onClick={()=>setMode("desktop")} aria-pressed={mode==="desktop"} aria-label="Desktop preview" className={`grid size-8 place-items-center rounded-md border hairline ${mode==="desktop"?"surface":""}`}><Monitor size={13}/></button><button onClick={()=>setMode("mobile")} aria-pressed={mode==="mobile"} aria-label="Mobile preview" className={`grid size-8 place-items-center rounded-md border hairline ${mode==="mobile"?"surface":""}`}><Smartphone size={13}/></button><button onClick={()=>setDark(!dark)} aria-pressed={dark} aria-label="Toggle preview theme" className="grid size-8 place-items-center rounded-md border hairline">{dark?<Sun size={13}/>:<Moon size={13}/>}</button></div></div>{tab==="preview"?<div className={`${dark?"dark bg-[#10110e] text-[#f1f2eb]":""} p-3 md:p-5`}><div className={`mx-auto overflow-hidden rounded-lg border hairline transition-[max-width] duration-300 ${mode==="mobile"?"max-w-[390px]":"max-w-full"}`}><ComponentPreview item={item}/></div></div>:<div className="relative bg-[#171815] text-[#e9eae4]"><pre className="max-h-[560px] overflow-auto p-5 text-xs leading-6 md:p-7"><code>{source}</code></pre><div className="absolute top-3 right-3"><CopyButton value={source}/></div></div>}</div>
 <div className="prose-flux max-w-3xl"><h2 id="installation">Installation</h2><p>Add the component and its peer dependencies with the themaginui CLI.</p><div className="flex items-center justify-between rounded-xl bg-[#171815] p-3 pl-5 text-white"><code className="!bg-transparent">{cmd}</code><CopyButton value={cmd}/></div><h2 id="usage">Usage</h2><pre><code>{`import { ${item.name.replaceAll(" ","")} } from "@/components/themaginui/${item.slug}";\n\n<${item.name.replaceAll(" ","")} variant="default" />`}</code></pre><h2 id="variants">Variants</h2><p>The component ships with <code>default</code>, <code>quiet</code>, and <code>expressive</code> visual variants. Each shares the same semantic markup and focus behavior.</p><div className="grid gap-3 sm:grid-cols-3">{["Default","Quiet","Expressive"].map((x,i)=><div className="rounded-xl border hairline p-4" key={x}><span className="mono text-[9px] muted">0{i+1}</span><b className="mt-5 block">{x}</b><p className="text-xs">For {i===0?"general product UI":i===1?"dense interfaces":"key moments"}.</p></div>)}</div><h2 id="props">API reference</h2><div className="overflow-auto rounded-xl border hairline"><table className="w-full text-left text-xs"><thead className="surface"><tr><th className="p-3">Prop</th><th>Type</th><th>Default</th><th>Description</th></tr></thead><tbody>{[["variant","default | quiet | expressive","default","Controls visual emphasis."],["disabled","boolean","false","Prevents interaction."],["className","string","—","Extends the root styles."],["reducedMotion","boolean","system","Overrides motion preference."]].map(r=><tr className="border-t hairline" key={r[0]}>{r.map((c,i)=><td className={`p-3 ${i?"muted":"mono"}`} key={c}>{c}</td>)}</tr>)}</tbody></table></div><h2 id="motion">Motion explanation</h2><p>A damped spring connects hover, focus, and entrance states. The transform-only animation remains GPU-friendly; opacity and translation are disabled when the user requests reduced motion.</p><h2 id="accessibility">Accessibility</h2><ul><li>Keyboard interaction follows the relevant WAI-ARIA pattern.</li><li>Focus indicators maintain at least 3:1 contrast against adjacent colors.</li><li>Decorative motion has no semantic meaning and respects <code>prefers-reduced-motion</code>.</li><li>Touch targets remain at least 44 × 44 CSS pixels.</li></ul><h2 id="customization">Customization</h2><p>Override semantic CSS tokens such as <code>--surface</code>, <code>--ink</code>, <code>--line</code>, and <code>--accent</code>. Structural classes can be composed with the exported <code>cn</code> utility.</p><h2>Related components</h2><div className="grid gap-3 sm:grid-cols-3">{related.map(x=><Link className="rounded-xl border hairline p-4 transition-transform hover:-translate-y-1" href={`/components/${x.slug}`} key={x.slug}><small className="mono text-[8px] uppercase muted">{x.category}</small><b className="mt-2 block text-sm">{x.name}</b></Link>)}</div></div></article>
 <aside className="hidden xl:block"><div className="sticky top-28 flex flex-col gap-3 border-l hairline pl-5 mono text-[9px] uppercase muted"><span className="mb-2 text-[var(--ink)]">On this page</span>{["Installation","Usage","Variants","Props","Motion","Accessibility","Customization"].map(x=><a className="hover:text-[var(--ink)]" href={`#${x.toLowerCase()}`} key={x}>{x}</a>)}<div className="mt-6 rounded-lg border hairline bg-[var(--raised)] p-4 normal-case"><b className="block text-[var(--ink)]">Accessibility</b><span className="mt-2 block text-sm text-[var(--success)]">Keyboard ready</span><small className="mt-1 block leading-4">Focus, semantics, contrast, and reduced motion documented.</small></div></div></aside></div></div></main>}
