export const docs = [
 {slug:"",title:"Introduction",description:"Build expressive interfaces with source-owned React components.",sections:[["What is themaginui?","themaginui is a source-first component registry for React 19. Components are added directly to your project, so styling, behavior, and accessibility remain under your control."],["Design principles","Motion explains state. APIs stay composable. Accessibility is structural. Defaults are polished, but never precious."]]},
 {slug:"installation",title:"Installation",description:"Configure a Next.js project and add your first component.",sections:[["Requirements","themaginui targets React 19, Next.js 16, Tailwind CSS v4, and Motion. TypeScript strict mode is recommended."],["Initialize","Run `pnpm dlx themaginui init`, review the generated design tokens, then add components with `pnpm dlx themaginui add magnetic-button`."]]},
 {slug:"tailwind",title:"Tailwind setup",description:"Connect themaginui tokens to Tailwind CSS v4.",sections:[["CSS-first configuration","Import Tailwind in your global stylesheet and define themaginui semantic tokens inside `:root`. Dark mode overrides the same stable token names."],["Class merging","Use the included `cn` helper to combine conditional classes without conflicting Tailwind utilities."]]},
 {slug:"cli",title:"CLI",description:"Search, inspect, and add registry components.",sections:[["Commands","Use `init` to configure a project, `list` to inspect the registry, `add` to install source, and `diff` to compare local components with their latest registry versions."],["Non-destructive updates","The CLI never overwrites a changed file without confirmation. Use `--dry-run` to inspect every planned write."]]},
 {slug:"manual-installation",title:"Manual installation",description:"Install any component without the CLI.",sections:[["Copy the source","Open the Code tab, copy the component and required utilities, then install the listed peer dependencies."],["Connect tokens","Map the semantic variables to your design system. Components do not rely on hard-coded brand colors."]]},
 {slug:"dark-mode",title:"Dark mode",description:"Ship light, dark, system, and high-contrast experiences.",sections:[["Theme provider","Wrap the application in `next-themes` and use a class attribute. themaginui previews can be toggled independently from the documentation shell."],["Contrast mode","High contrast is token-driven and keeps layout dimensions stable when it is enabled."]]},
 {slug:"theming",title:"Theming",description:"Adapt themaginui to your product without forking behavior.",sections:[["Semantic tokens","Surfaces, text, borders, accents, and semantic states use CSS custom properties. Change the meaning once and every component follows."],["Shape and type","Radius, spacing, and typography are independent layers. Components use inheritance wherever practical."]]},
 {slug:"animations",title:"Animations",description:"Understand the motion language and performance model.",sections:[["Purpose before polish","Entrance motion establishes hierarchy, shared transitions preserve context, and springs communicate direct manipulation."],["Performance","Animations favor transforms and opacity. Scroll-driven effects are bounded, and all loops pause outside the viewport."]]},
 {slug:"accessibility",title:"Accessibility",description:"Keyboard, screen-reader, contrast, and motion guidance.",sections:[["Baseline","Interactive primitives follow established ARIA patterns, preserve visible focus, and maintain 44-pixel touch targets."],["Testing","Test real task flows with keyboard navigation, VoiceOver or NVDA, browser zoom, forced colors, and reduced motion."]]},
 {slug:"performance",title:"Performance",description:"Keep animated interfaces responsive.",sections:[["Client boundaries","Documentation and layout remain Server Components. Only previews and direct interactions cross the client boundary."],["Bundle discipline","Components are source-owned and tree-shake naturally. Import icons individually and lazy-load expensive canvas or WebGL effects."]]},
 {slug:"contributing",title:"Contributing",description:"Propose components, fixes, and documentation improvements.",sections:[["Quality bar","Every contribution includes types, keyboard behavior, reduced motion, examples, and documentation."],["Review","Changes are reviewed for API clarity, composability, performance, and visual purpose before inclusion."]]},
 {slug:"roadmap",title:"Roadmap",description:"What the project is building next.",sections:[["Near term","Registry namespaces, visual regression fixtures, framework adapters, and community collections are in progress."],["Long term","themaginui will remain source-first while expanding its tooling for teams maintaining private registries."]]},
 {slug:"migration",title:"Migration guides",description:"Upgrade themaginui while keeping product behavior stable.",sections:[["Version policy","Behavioral changes ship with migration notes and codemods when mechanical updates are possible."],["Component ownership","Because source lives in your repository, upgrades are explicit diffs rather than surprise runtime changes."]]},
 {slug:"faq",title:"FAQ",description:"Common questions about ownership, licensing, and compatibility.",sections:[["Can I use themaginui commercially?","Yes. The component source is MIT licensed and can be modified for commercial products."],["Is shadcn/ui required?","No. themaginui shares source-first values and can use Radix primitives, but each component documents its actual dependencies."]]},
 {slug:"examples",title:"Examples",description:"Patterns for composing themaginui components into real products.",sections:[["Dashboard shell","Combine Island Navbar, Activity Table, Metric Bento, and Command Surface for a keyboard-first operations dashboard."],["Launch page","Pair Editorial Hero, Logo Marquee, Product Bento, Focus Testimonial, and Simple Pricing for a restrained product launch."]]}
] as const;
export function getDoc(slug:string){return docs.find(x=>x.slug===slug)}
