export type LegalDocument = { title:string; summary:string; updated:string; sections:{title:string; paragraphs:string[]}[] };
export const legalDocuments:Record<string,LegalDocument>={
 privacy:{title:"Privacy Policy",summary:"How themaginui handles information when you browse the site, contact us, or use optional services.",updated:"August 1, 2026",sections:[
  {title:"Information we collect",paragraphs:["We receive technical request information that web servers ordinarily process, including IP address, browser type, requested URL, timestamps, and referring page. We may collect aggregate product analytics when analytics are enabled.","If you contact us or purchase a product, we receive the information you provide, such as your name, email address, message, billing contact, and transaction reference. Payment card details are processed by the payment provider and are not stored by themaginui."]},
  {title:"How information is used",paragraphs:["We use information to operate and secure the website, respond to requests, deliver purchases, understand documentation quality, prevent abuse, and satisfy legal obligations. We do not sell personal information or build cross-site advertising profiles."]},
  {title:"Cookies and analytics",paragraphs:["Essential storage may remember theme and interface preferences. If privacy-respecting analytics are enabled, they are used to understand aggregate usage. You can restrict storage through your browser settings, though some preferences may no longer persist."]},
  {title:"Sharing and retention",paragraphs:["Information is shared only with infrastructure, analytics, communication, and payment providers needed to operate the service, or when required by law. Records are retained only as long as needed for their stated purpose, security, accounting, and legal requirements."]},
  {title:"Your choices",paragraphs:["Depending on your location, you may request access, correction, deletion, restriction, or portability of personal information. Contact privacy@themaginui.dev. We may verify the request before acting on it."]},
  {title:"International processing and changes",paragraphs:["Service providers may process information in countries other than yours with appropriate contractual safeguards. Material policy changes will be reflected by the updated date on this page."]}
 ]},
 terms:{title:"Terms of Use",summary:"The rules that apply when accessing themaginui, its registry, documentation, and paid resources.",updated:"August 1, 2026",sections:[
  {title:"Using the service",paragraphs:["You may browse the site and use the component source subject to these terms and the applicable license. You must not interfere with service operation, probe systems without permission, distribute malware, evade access controls, or use the service unlawfully."]},
  {title:"Accounts and purchases",paragraphs:["You are responsible for activity under your account and for keeping credentials secure. Prices and included resources are shown before purchase. Unless required by law or stated at checkout, digital purchases are non-refundable after access has been provided."]},
  {title:"Open-source and paid resources",paragraphs:["Files expressly distributed under the MIT License remain governed by that license. Templates, design files, private registry tools, and other paid resources may have separate license terms presented with the resource. Purchasing access does not transfer trademarks or ownership of the service."]},
  {title:"Availability and changes",paragraphs:["We may improve, replace, suspend, or discontinue parts of the service. We aim to communicate material changes, but do not guarantee uninterrupted availability. Preview and experimental features may change without notice."]},
  {title:"Warranties and liability",paragraphs:["The service is provided as available without warranties to the maximum extent permitted by law. themaginui is not liable for indirect, incidental, special, consequential, or lost-profit damages arising from use of the service."]},
  {title:"Contact and governing terms",paragraphs:["Questions about these terms can be sent to legal@themaginui.dev. If any provision is unenforceable, the remaining provisions continue in effect. Updated terms apply from the date shown above."]}
 ]},
 license:{title:"MIT License",summary:"The license for source files explicitly identified as part of the open-source component collection.",updated:"Copyright © 2026 themaginui",sections:[
  {title:"Permission",paragraphs:["Permission is hereby granted, free of charge, to any person obtaining a copy of the licensed software and associated documentation files, to deal in the software without restriction, including the rights to use, copy, modify, merge, publish, distribute, sublicense, and sell copies."]},
  {title:"Condition",paragraphs:["The copyright notice and this permission notice must be included in all copies or substantial portions of the software."]},
  {title:"Warranty disclaimer",paragraphs:["The software is provided “as is”, without warranty of any kind, express or implied, including but not limited to merchantability, fitness for a particular purpose, and noninfringement."]},
  {title:"Limitation of liability",paragraphs:["In no event shall the authors or copyright holders be liable for any claim, damages, or other liability arising from, out of, or in connection with the software or its use."]},
  {title:"Scope",paragraphs:["This license applies to files marked as MIT licensed in the public component registry. Paid templates, design assets, brand marks, and third-party dependencies may be governed by their own terms and licenses."]}
 ]}
};
